set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",*256col*:RGB"

set -s set-clipboard on
set -g mouse on
set -g prefix C-Space
set -g history-limit 10000
set -g base-index 1
set -g renumber-windows on
set -s escape-time 0

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind % split-window -v -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind Space last-window

set -g status-bg colour234
set -g status-fg colour137
set -g status-right-length 50
set -g status-left-length 20
set -g status-left ''
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '
